import os

# Определяем текущее окружение
ENVIRONMENT: str = os.getenv("ENVIRONMENT", "development")
BASE_URL = (
    os.getenv("MAIN_PAGE", "https://preprod.softmg.ru/")
    if ENVIRONMENT == "development"
    else os.getenv("PROD_PAGE", "https://softmg.ru/")
)


class PageConfig:

    def __init__(self, base_url: str = BASE_URL):
        self.base_url = base_url
        self.pages = {
            "base_page": {
                "name": "base_page",
                "title": "",
                "description": "",
                "url_page": self.base_url,
                "api_url": self.base_url + "api/v2/page/main"
            },
            # "restoran": {
            #     "name": "restoran",
            #     "title": "",
            #     "description": "",
            #     "url_page": self.base_url + "examples/restoran/",
            # },
            # "auto": {
            #     "name": "auto",
            #     "title": "",
            #     "description": "",
            #     "url_page": self.base_url + "examples/auto/",
            # },
            # "nedviga": {
            #     "name": "nedviga",
            #     "title": "",
            #     "description": "",
            #     "url_page": self.base_url + "examples/nedvigimost/",
            # },
            # "premium": {
            #     "name": "premium",
            #     "title": "",
            #     "description": "",
            #     "url_page": self.base_url + "examples/premium/",
            # },
            # "adaptiv": {
            #     "name": "adaptiv",
            #     "title": "",
            #     "description": "",
            #     "url_page": self.base_url + "examples/adaptiv/",
            # },
            # "bizness": {
            #     "name": "bizness",
            #     "title": "",
            #     "description": "",
            #     "url_page": self.base_url + "examples/bizness/",
            # },
            # "stroy-comp": {
            #     "name": "stroy-comp",
            #     "title": "",
            #     "description": "",
            #     "url_page": self.base_url + "examples/stroitelnie-kompanyy/",
            # },
            # "remont": {
            #     "name": "remont",
            #     "title": "",
            #     "description": "",
            #     "url_page": self.base_url + "examples/remont-otdelka/",
            # },
            # "health": {
            #     "name": "health",
            #     "title": "",
            #     "description": "",
            #     "url_page": self.base_url + "examples/?tag=health",
            # },
            # "med-klinika": {
            #     "name": "med-klinika",
            #     "title": "",
            #     "description": "",
            #     "url_page": self.base_url + "examples/med-klinika/",
            # },
            "uslugi": {
                "name": "uslugi",
                "title": "Услуги",
                "description": "",
                "url_page": self.base_url + "uslugi/",
                "api_url": self.base_url + "api/v2/page/offers"
            },
            "calculator": {
                "name": "calculator",
                "title": "Калькулятор услуг",
                "description": "",
                "url_page": self.base_url + "calculator/",
                "api_url": self.base_url + "api/v2/page/calculator"
            },
            "examples": {
                "name": "examples",
                "title": "Кейсы",
                "description": "",
                "url_page": self.base_url + "examples/",
                "api_url": self.base_url + "api/v2/page/examples",
            },
            "about-company": {
                "name": "about-company",
                "title": "О компании Soft Media Group",
                "description": "",
                "url_page": self.base_url + "about-company/",
                "api_url": self.base_url + "api/v2/page/about-company/",
            },
            "contacts": {  # страница без API
                "name": "contacts",
                "title": "Контакты",
                "description": "",
                "url_page": self.base_url + "contacts/",
            },

            "development": {
                "name": "development",
                "title": "Разработка сайтов",
                "description": "",
                "url_page": self.base_url + "development/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/",
            },
            "it-autstaffing": {
                "name": "it-autstaffing",
                "title": "Аутстаффинг IT-специалистов",
                "description": "",
                "url_page": self.base_url + "it-autstaffing/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/it-autstaffing/",
            },
            "outsource": {
                "name": "outsource",
                "title": "Аутсорс IT",
                "description": "",
                "url_page": self.base_url + "outsource/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/outsource/",
            },
            "application-development": {
                "name": "application-development",
                "title": "Разработка приложений",
                "description": "",
                "url_page": self.base_url + "application-development/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/application-development/",
            },
            "razrabotka-ai": {
                "name": "razrabotka-ai",
                "title": "Искусственный интеллект для бизнеса – решения, которые работают",
                "description": "",
                "url_page": self.base_url + "razrabotka-ai/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/razrabotka-ai/",
            },
            "biznes-agenty": {
                "name": "biznes-agenty",
                "title": "Разработка ИИ агентов для бизнеса",
                "description": "",
                "url_page": self.base_url + "razrabotka-ai/biznes-agenty/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/razrabotka-ai/biznes-agenty/",
            },
            "chat-boty": {
                "name": "chat-boty",
                "title": "Чат-боты для бизнеса",
                "description": "",
                "url_page": self.base_url + "razrabotka-ai/chat-boty/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/razrabotka-ai/chat-boty/",
            },
            "razrabotka-po": {
                "name": "razrabotka-po",
                "title": "Разработка ПО",
                "description": "",
                "url_page": self.base_url + "razrabotka-po/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/razrabotka-po/",
            },
            "devops": {
                "name": "devops",
                "title": "DevOps: стабильная работа и быстрое развитие ваших IT-систем",
                "description": "",
                "url_page": self.base_url + "uslugi/devops/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/uslugi/devops/",
            },
            "support": {
                "name": "support",
                "title": "Сопровождение и поддержка сайтов",
                "description": "",
                "url_page": self.base_url + "support/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/support/",
            },
            "promotion": {
                "name": "promotion",
                "title": "Поисковое продвижение",
                "description": "Поисковое продвижение",
                "url_page": self.base_url + "promotion/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/promotion/",
            },
            "other_services": {
                "name": "other_services",
                "title": "Услуги",
                "description": "",
                "url_page": self.base_url,
            },
            "article": {
                "name": "article",
                "title": "Статьи",
                "description": "",
                "url_page": self.base_url + "article/",
                "api_url": self.base_url + "api/v2/page/articles",
            },
            "news": {
                "name": "news",
                "title": "Новости компании",
                "description": "",
                "url_page": self.base_url + "news/",
                "api_url": self.base_url + "api/v2/page/news",
            },
            "reviews": {
                "name": "reviews",
                "title": "Отзывы",
                "description": "",
                "url_page": self.base_url + "reviews/",
                "api_url": self.base_url + "api/v2/page/reviews",
            },
            "vakansii": {
                "name": "vakansii",
                "title": "Карьера в SMG",
                "description": "",
                "url_page": self.base_url + "vakansii/",
                "api_url": self.base_url + "api/v2/page/vakansii",
            },
            "referral": {
                "name": "referral",
                "title": "Реферальная программа ГК Soft Media Group",
                "description": "",
                "url_page": self.base_url + "referral/",
                "api_url": self.base_url + "api/v2/page/referral",
            },
            "development_framework": {
                "name": "development_framework",
                "title": "Cайты на фреймворке",
                "description": "",
                "url_page": self.base_url + "development/framework/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/framework/",
            },
            "development_corporate": {
                "name": "development_corporate",
                "title": "Создание корпоративного сайта",
                "description": "",
                "url_page": self.base_url + "development/corporate/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/corporate/",
            },
            "shop": {
                "name": "development_shop",
                "title": "Создание интернет-магазина",
                "description": "",
                "url_page": self.base_url + "development/shop/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/shop/",
            },
            "interactive": {
                "name": "development_interactive",
                "title": "Создание интерактивных сайтов",
                "description": "",
                "url_page": self.base_url + "development/interactive/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/interactive/",
            },
            "design": {
                "name": "development_design",
                "title": "Разработка дизайна сайта",
                "description": "",
                "url_page": self.base_url + "development/design/",
            },
            "card": {
                "name": "development_card",
                "title": "Создание сайта-визитки",
                "description": "",
                "url_page": self.base_url + "development/card/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/card/",
            },
            "landing": {
                "name": "landing",
                "title": "Разработка сайтов Landing Page",
                "description": "",
                "url_page": self.base_url + "development/landing-page/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/landing-page/",
            },
            "application_ios": {
                "name": "application_ios",
                "title": "Создание приложений для iOS",
                "description": " ",
                "url_page": self.base_url + "application-development/ios/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/application-development/ios/",
            },
            "application_android": {
                "name": "application_android",
                "title": "Создание приложений под Android",
                "description": " ",
                "url_page": self.base_url + "application-development/android/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/application-development/android/",
            },
            "development_backbone": {
                "name": "development_backbone",
                "title": "Разработка приложений на Backbone",
                "description": " ",
                "url_page": self.base_url + "development/backbone/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/backbone/",
            },
            "application_mongodb": {
                "name": "application_mongodb",
                "title": "MongoDB",
                "description": "",
                "url_page": self.base_url + "application-development/mongodb/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/application-development/mongodb/",
            },
            "application_java": {
                "name": "application_java",
                "title": "Разработка приложений на Java",
                "description": "",
                "url_page": self.base_url + "application-development/java/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/application-development/java/",
            },
            "application_smartphone": {
                "name": "application_smartphone",
                "title": "Приложения для смартфонов",
                "description": "",
                "url_page": self.base_url + "application-development/smartphone/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/application-development/smartphone/",
            },
            "javascript_react": {
                "name": "javascript_react",
                "title": "Фреймворк React.js",
                "description": "",
                "url_page": self.base_url + "development/framework/javascript-react/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/framework/javascript-react/",
            },
            "react_native": {
                "name": "react_native",
                "title": "Мобильные приложения на фреймворк React Native",
                "description": "",
                "url_page": self.base_url + "application-development/react-native/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/application-development/react-native/",
            },
            "support_netcat": {
                "name": "support_netcat",
                "title": "Техподдержка сайтов на Netcat",
                "description": "",
                "url_page": self.base_url + "support/netcat/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/support/netcat/",
            },
            "support_wordpress": {
                "name": "support_wordpress",
                "title": "Техподдержка сайтов на Wordpress",
                "description": "",
                "url_page": self.base_url + "support/wordpress/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/support/wordpress/",
            },
            "support_bitrix": {
                "name": "support_bitrix",
                "title": "Техподдержка сайтов на Bitrix",
                "description": "",
                "url_page": self.base_url + "support/bitrix/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/support/bitrix/",
            },
            "sozdanie-corporate": {
                "name": "sozdanie-corporate",
                "title": "Разработка и продвижение сайта компании",
                "description": "",
                "url_page": self.base_url + "promotion/sozdanie-corporate/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/promotion/sozdanie-corporate/",
            },
            "internet-magazin": {
                "name": "internet-magazin",
                "title": "Создание и продвижение интернет-магазина",
                "description": "",
                "url_page": self.base_url + "promotion/internet-magazin/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/promotion/internet-magazin/",
            },
            "development-seo": {
                "name": "development-seo",
                "title": "Создание сайтов для СЕО-продвижения",
                "description": "",
                "url_page": self.base_url + "development/seo/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/seo/",
            },
            "promotion-yandex": {
                "name": "promotion-yandex",
                "title": "Продвижение сайтов под Яндекс",
                "description": "",
                "url_page": self.base_url + "promotion/yandex",
                "api_url": self.base_url + "api/v2/offers/slug?url=/promotion/yandex/",
            },
            "promotion-google": {
                "name": "promotion-google",
                "title": "Продвижение сайтов под Google",
                "description": "",
                "url_page": self.base_url + "promotion/google",
                "api_url": self.base_url + "api/v2/offers/slug?url=/promotion/google/",
            },
            "integraciya-1c": {
                "name": "integraciya-1c",
                "title": "Интеграция 1С: полная автоматизация торговли",
                "description": "",
                "url_page": self.base_url + "integraciya-1c",
                "api_url": self.base_url + "api/v2/offers/slug?url=/integraciya-1c/",
            },
            "automated-testing": {
                "name": "automated-testing",
                "title": "Интеграция 1С: полная автоматизация торговли",
                "description": "",
                "url_page": self.base_url + "uslugi/automated-testing/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/uslugi/automated-testing/",
            },
            "dorabotka-saytov": {
                "name": "dorabotka-saytov",
                "title": "Доработка сайтов",
                "description": "",
                "url_page": self.base_url + "dorabotka-saytov/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/dorabotka-saytov/",
            },
            "testirovanie": {
                "name": "testirovanie",
                "title": "Повышаем качество программных продуктов",
                "description": "",
                "url_page": self.base_url + "testirovanie/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/testirovanie/",
            },
            "development-design": {
                "name": "development-design",
                "title": "Разработка дизайна сайта",
                "description": "",
                "url_page": self.base_url + "development/design",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/design/",
            },
            "systems-analyst": {
                "name": "systems-analyst",
                "title": "???",
                "description": "",
                "url_page": self.base_url + "systems-analyst/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/systems-analyst/",
            },
            "development-symfony": {
                "name": "development-symfony/",
                "title": "Создание сайтов на Symfony",
                "description": "",
                "url_page": self.base_url + "development/symfony/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/symfony/",
            },
            "development-laravel": {
                "name": "development-laravel/",
                "title": "Сайты на Laravel",
                "description": "",
                "url_page": self.base_url + "development/laravel/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/laravel/",
            },
            "development-yii": {
                "name": "development-yii",
                "title": "Сайты на Yii",
                "description": "",
                "url_page": self.base_url + "development/yii/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/yii/",
            },
            "development-zend": {
                "name": "development-zend",
                "title": "Сайты на Zend",
                "description": "",
                "url_page": self.base_url + "development/zend/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/zend/",
            },
            "development-codeigniter": {
                "name": "development-codeigniter",
                "title": "Сайты на Codeigniter",
                "description": "",
                "url_page": self.base_url + "development/codeigniter/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/codeigniter/",
            },
            "development-cakephp": {
                "name": "development-cakephp",
                "title": "Разработка сайтов и приложений на Cakephp",
                "description": "",
                "url_page": self.base_url + "development/cakephp/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/cakephp/",
            },
            "development-framework-javascript": {
                "name": "development-javascript",
                "title": "Фреймворки JavaScript",
                "description": "",
                "url_page": self.base_url + "development/framework/javascript/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/framework/javascript/",
            },
            "development-framework-java": {
                "name": "development-java",
                "title": "Фреймворки Java",
                "description": "",
                "url_page": self.base_url + "development/framework/java/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/framework/java/",
            },
            "development-corporate-wordpress": {
                "name": "corporate-wordpress",
                "title": "Корпоративные сайты на Wordpress",
                "description": "",
                "url_page": self.base_url + "development/corporate/wordpress/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/corporate/wordpress/",
            },
            "development-corporate-bitrix": {
                "name": "corporate-bitrix",
                "title": "Разработка корпоративного сайта на Bitrix",
                "description": "",
                "url_page": self.base_url + "development/corporate/bitrix/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/corporate/bitrix/",
            },
            "shop-1c-bitrix": {
                "name": "shop-1c-bitrix",
                "title": "Интернет-магазин на 1С Битрикс",
                "description": "",
                "url_page": self.base_url + "development/shop/1c-bitrix/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/shop/1c-bitrix/",
            },
            "shop-virtuemart": {
                "name": "shop-virtuemart",
                "title": "Интернет-магазин на Virtuemart",
                "description": "",
                "url_page": self.base_url + "development/shop/virtuemart/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/shop/virtuemart/",
            },
            "shop-wordpress": {
                "name": "shop-wordpress",
                "title": "Интернет-магазин на WordPress",
                "description": "",
                "url_page": self.base_url + "development/shop/wordpress/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/shop/wordpress/",
            },
            "shop-opencart": {
                "name": "shop-opencart",
                "title": "Создание сайтов на OpenCart",
                "description": "",
                "url_page": self.base_url + "development/shop/opencart/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/shop/opencart/",
            },
            "development-umicms": {
                "name": "development-umicms",
                "title": "Создание сайта на UMI.CMS",
                "description": "",
                "url_page": self.base_url + "development/umicms/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/umicms/",
            },
            "shop-magento": {
                "name": "development-shop-magento",
                "title": "Разработка интернет-магазин на Magento",
                "description": "",
                "url_page": self.base_url + "development/shop/magento/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/shop/magento/",
            },
            "shop-ubercart": {
                "name": "development-shop-ubercart",
                "title": "Создание сайта на Ubercart",
                "description": "",
                "url_page": self.base_url + "development/shop/ubercart/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/shop/ubercart/",
            },
            "shop-prestashop": {
                "name": "development-shop-prestashop",
                "title": "Разработка интернет-магазинов на CMS PrestaShop",
                "description": "",
                "url_page": self.base_url + "development/shop/prestashop/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/shop/prestashop/",
            },
            "shop-oscommerce": {
                "name": "development-shop-oscommerce",
                "title": "Интернет-магазин на osCommerce",
                "description": "",
                "url_page": self.base_url + "development/shop/oscommerce/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/shop/oscommerce/",
            },
            "development-netcat": {
                "name": "development-netcat",
                "title": "Создание сайта на NetCat",
                "description": "",
                "url_page": self.base_url + "development/netcat/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/netcat/",
            },
            "shop-shopscript": {
                "name": "shop-shopscript",
                "title": "Создание сайтов на Shop Script",
                "description": "",
                "url_page": self.base_url + "development/shop/shopscript/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/shop/shopscript/",
            },
            "shop-pod-kluch": {
                "name": "shop-pod-kluch",
                "title": "Интернет-магазин под ключ",
                "description": "",
                "url_page": self.base_url + "development/shop/pod-kluch/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/shop/pod-kluch/",
            },
            "card-bitrix": {
                "name": "card-bitrix",
                "title": "Сайт-визитка на Bitrix",
                "description": "",
                "url_page": self.base_url + "development/card/bitrix/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/card/bitrix/",
            },
            "development-drupal": {
                "name": "development-drupal",
                "title": "Разработка сайтов на Drupal",
                "description": "",
                "url_page": self.base_url + "development/drupal/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/drupal/",
            },
            "development-joomla": {
                "name": "development-joomla",
                "title": "Разработка сайтов на Joomla",
                "description": "",
                "url_page": self.base_url + "development/joomla/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/joomla/",
            },
            "development-wordpress": {
                "name": "development-wordpress",
                "title": "Разработка сайтов на Wordpress",
                "description": "",
                "url_page": self.base_url + "development/wordpress/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/development/wordpress/",
            },
            "software-product-development": {
                "name": "software-product-development",
                "title": "Разработка программных продуктов: решения под ключ",
                "description": "",
                "url_page": self.base_url + "software-product-development/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/software-product-development/",
            },
            "razrabotka-po-django": {
                "name": "razrabotka-po-django",
                "title": "Разработка на Django",
                "description": "",
                "url_page": self.base_url + "razrabotka-po/django/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/razrabotka-po/django/",
            },
            "razrabotka-po-python": {
                "name": "razrabotka-po-python",
                "title": "Разработка на Python",
                "description": "",
                "url_page": self.base_url + "razrabotka-po/python/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/razrabotka-po/python/",
            },
            "veb-razrabotka-python": {
                "name": "veb-razrabotka-python",
                "title": "Веб разработка на Python",
                "description": "",
                "url_page": self.base_url + "razrabotka-po/veb-razrabotka-python/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/razrabotka-po/veb-razrabotka-python/",
            },
            "razrabotka-po-golang": {
                "name": "razrabotka-po-golang",
                "title": "Разработка программного обеспечения на Golang",
                "description": "",
                "url_page": self.base_url + "razrabotka-po/golang/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/razrabotka-po/golang/",
            },
            "razrabotka-po-net": {
                "name": "razrabotka-po-net",
                "title": "Разработка на .net",
                "description": "",
                "url_page": self.base_url + "razrabotka-po/net/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/razrabotka-po/net/",
            },
            "unity": {
                "name": "unity",
                "title": "Разработка на Unity",
                "description": "",
                "url_page": self.base_url + "unity/",
                "api_url": self.base_url + "api/v2/offers/slug?url=/unity/",
            },
        }

    def get_page_data(self, page_name: str) -> dict:
        """Возвращает данные страницы по ее имени."""
        if page_name in self.pages:
            return self.pages[page_name]
        else:
            raise ValueError(f"Страница '{page_name}' не найдена в PageConfig.")


config = PageConfig()
